export const FORMULARIO_EQUIPO = 'FORMULARIO_EQUIPO';
export const OBTENER_EQUIPOS = 'OBTENER_EQUIPOS';
export const AGREGAR_EQUIPO = 'AGREGAR_EQUIPO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const EQUIPO_ACTUAL = 'EQUIPO_ACTUAL';
export const ELIMINAR_EQUIPO = 'ELIMINAR_EQUIPO';